### ISSUE TITLE
Source code request

### ISSUE THREAD

**Issue by michaeloliverx** [CraigChrist8239/The-Tesseract-on-Xbox-360-for-Black-Ops-2#1]
Hi there, first off I apologise for opening an issue as a means of contact but LinkedIn doesn't let me message without connecting first.

I think you are the author of ZoneHandler? If so would you be willing to release the source for it?

I have a keen interest in COD4 and plan to do some research on fastfile editing/compilation as a hobby project. I'd rather build upon existing work than start from scratch!

Kind regards

**Comment by rheard** [comment]
@michaeloliverx  I'm sorry but that code is no longer available. You'll need to look at other public projects instead, find some other non-public information to learn from, or attempt to decompile the app (I cannot remember if I used obfuscation but I may have).

If you'd like to learn why or discuss more you can contact me on Discord or by private message on Steam or Se7enSins via the username CraigChrist8329, or even on RuneScape via the username CraigChrist

I'm afraid thats all the contact information I'm willing to put online
